### ISSUE TITLE
Add section for text editor extensions. 

### ISSUE THREAD

**Issue by benreckas** [benreckas/the-dev-toolkit#17]
Live Server, Bracket Pair Colorizer, etc...

**Comment by maciekChmura** [comment]
I have some good candidates.
Can I make a PR?

**Comment by benreckas** [comment]
Have at it!

**Comment by maciekChmura** [comment]
Cool.
I will work on this today.

**Comment by maciekChmura** [comment]
Hello.
I made a PR.
What do you think about it?

**Comment by benreckas** [comment]
Looks good! Merged into development. #19
